### ISSUE TITLE
sound alerts

### ISSUE THREAD

**Issue by cannonerd** [meri-imperiumi/curiosity#5]
- anchor alarm (alien alarm)
- state change
- voronoi jingle
- crew welcome
- optional watch bell/ time announcements

**Comment by bergie** [comment]
Done via 5521a9133215241cf4e38d4d4aa36cd6d7a408fd

Though, I think the deps for audio notifier (https://github.com/meri-imperiumi/signalk-audio-notifications) are not properly handled in Ansible playbook yet
